import { Footer, Navbar } from '@/components';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '../../context/ThemeContext';
import { AuthProvider } from '@/components/authProvider/AuthProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Carlos Dev',
  description: 'Generated by Carlos Dev',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <div className="container">
              <Navbar />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
